# Iteration Over Lists and Vectors in Python

In [28]:
import numpy as np

# Creates two arrays, one randomly, and prints them
v1 = np.array([4,2,6,1])
v2 = np.random.rand(4)
print(v1, "\n", v2)

[4 2 6 1] 
 [0.04744316 0.95579802 0.43085261 0.26136051]


In [29]:
# Squares all items in array v1
w = [x**2 for x in v1]

In [30]:
w

[16, 4, 36, 1]

In [31]:
# Returns the 'shape' of the array as a tuple. This array contains one element, itself containing 4 elements. 
v1.shape

(4,)

In [32]:
n, = v1.shape
print(n)

# Returns an array of the same size, filled with zeroes
v3 = np.zeros(n)
print(v3)

# each element in v3 becomes the square of each element in v1
for j in range(n):
    v3[j] = v1[j]**2
print(v3)

# each element in v4 becomes the square of each element in v1
v4 = v1**2
print(v4)

4
[0. 0. 0. 0.]
[16.  4. 36.  1.]
[16  4 36  1]


# Matrix and Vector Multiplication

In [33]:
import numpy as np
u = np.array([1,2,3,4])
v = np.array([2,3,0,1])
print(u.shape, v.shape)
print(u, v)

(4,) (4,)
[1 2 3 4] [2 3 0 1]


In [34]:
# Prints an array containing the product of each element of u and v 
# Then prints the 'dot product' of u and v 
print(u*v, u.dot(v))

[2 6 0 4] 12


In [35]:
# Reshapes the array into a column vector with 4 rows 
cu = u.reshape(4, 1)
print(cu.shape, "\n")
print(cu)

(4, 1) 

[[1]
 [2]
 [3]
 [4]]


In [36]:
print(cu * v) # hadamard product of cu and v

[[ 2  3  0  1]
 [ 4  6  0  2]
 [ 6  9  0  3]
 [ 8 12  0  4]]


In [37]:
m1 = np.array([[1,2], [3,4]]) 
m2 = np.array([[2,1], [-2,3]])
print(m1, "\n\n", m2)

[[1 2]
 [3 4]] 

 [[ 2  1]
 [-2  3]]


In [38]:
# element-wise multiplicaiton and matrix multiplication
print(m1*m2, "\n\n", m1.dot(m2))

[[ 2  2]
 [-6 12]] 

 [[-2  7]
 [-2 15]]


In [39]:
a = np.array([[1,0,0,0],
             [0,1,1,0],
             [0,0,1,2]])

In [40]:
print(a.dot(u), "\n")
print(a.dot(cu))

[ 1  5 11] 

[[ 1]
 [ 5]
 [11]]


In [41]:
b = np.array([[3,1], [2,2], [1,3], [1,11]])
print(a, "\n\n\n", b)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]] 


 [[ 3  1]
 [ 2  2]
 [ 1  3]
 [ 1 11]]


In [42]:
print(a.dot(b))

[[ 3  1]
 [ 3  5]
 [ 3 25]]


# Transpose of a Matrix

In [43]:
a.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [44]:
print(a.shape, a.T.shape)

(3, 4) (4, 3)


```python
u.dot(a)
```

This line will return an error as a dot product can only be done with matrices of the same shape.

In [45]:
u.dot(a.T) # these are now the same size, and hence work 

array([ 1,  5, 11])

# Nested Loop in Python

In [46]:
# old-fasioned code to multiply each element of 'a' by 2
(m ,n) = a.shape
c = np.zeros((m,n), "int32")
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [47]:
for i in range(m):
    for j in range(n):
        c[i,j] = a[i,j] * 2

print(c)

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [48]:
# easiest way
print(a*2)

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


# Exercises
### Matrix by Vector Multiplication without NumPy

In [49]:
def multiply_matrix_by_vector(m, v): 
    R, C = m.shape
    V, = v.shape
    u = np.array([])

    if C != V:
        print("\nArray and Vector shapes are not matching.\n")
        return None

    # u = m multiplied by v, initialise u to 0 
    u = np.zeros(R)

    for i in range(R):
        for j in range(C):
            u[i] += m[i][j] * v[j]

    return u

In [50]:
m1 = np.array([[1,2], [3,4]])
v1 = np.array([5, 6])
m3 = multiply_matrix_by_vector(m1, v1)

print(m3)

[17. 39.]


### Matrix by Matrix Multiplication without NumPy

In [51]:
def multiply_matrices(a, b):
    R1,C1 = a.shape
    R2,C2 = b.shape 

    if C1 != R2:
        print("\nArray shapes are not matching.\n")
        return None
    
    c = np.zeros((R1,C2))

    for i in range(R1):
        for j in range(C2):
            for k in range (C1):
                c[i][j] += a[i][k] * b[k][j]

    return c

In [52]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
m3 = multiply_matrices(m1, m2)

print(m3)

[[19. 22.]
 [43. 50.]]


### Multiplying a Vector by a List of Matrices

In [53]:
def f(x, matrices):
    y = x
    for m in matrices:
        y = m.dot(y)

    return y

In [54]:
v1 = np.array([1,2])
matrix_list = [np.array([[1,2],[3,4]]), np.array([[1,2], [3,4]])]

print(f(v1, matrix_list))

[27 59]
