This a makey-upey neural network with 1 layer of 5 neurons which is the output layer.
Each input has 4 values and is associated with desired output with 5 values. All this requires a 5 by 4 weight matrix.
16 sample inputs and corresponding desired outputs are provided.

Yout task is to write code for feedforward() and getCost().

Then you are finally asked to add another layer to the network.

In [49]:
import numpy as np

def sigm(z):
    return 1.0 / (1.0 + np.exp(-z))

In [50]:
inputs = np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],
                [0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],
                [1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],
                [1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])

# These target vectors or desired output have no meaning.
targets = np.array([[1,0,0,0,0],[1,0,0,0,0],[0,1,0,0,0],[0,1,0,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,1,0,0,0],[0,0,1,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],
                   [0,0,0,0,1],[0,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0]])
print(inputs, '\n')
print(inputs.shape, '\n')
print(targets, '\n')
print(targets.shape)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] 

(16, 4) 

[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]] 

(16, 5)


In [51]:
# NN with 4 inputs and 5 outputs

class NN(object):
    def __init__(self):
        np.random.seed(2021)
        self.w = np.random.randn(5,4) # weights matrix with 5 rows and 4 cols
        self.b = np.random.randn(5,1) # 5 item column vector containing biases
    
    def feedforward(self, x):
        # Input layer to hidden layer
        z_hidden = np.dot(self.w, x.reshape(4, 1)) + self.b
        a_hidden = sigm(z_hidden)

        return a_hidden

    def getCost(self, xs, ys):
        cost = 0.0
        # Note that each input x from xs and corresponding desired output y from ys
        # are vectors of shape (4,) and (5,). They must first be rehaped into column
        # vectors of shapes (4,1) and (5,1).

        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)
            y = ys[i].reshape(5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)
        
            
        return cost/16.0

In [52]:
nn = NN()
print(nn.w, '\n')
print(nn.b)

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]
 [ 0.10641374  0.42215483  0.12420684 -0.83795346]
 [ 0.4090157   0.10275122 -1.90772239  1.1002243 ]
 [-1.40232506 -0.22508127 -1.33620597  0.30372151]] 

[[-0.72015884]
 [ 2.5449146 ]
 [ 1.31729112]
 [ 0.0726303 ]
 [-0.25610814]]


In [53]:
# Test feed forward on first input vector
# The input vector (shape 4,) must first be reshaped to a column vector (shape 4,1)
nn.feedforward(inputs[0].reshape(4,1))

array([[0.32735801],
       [0.92723113],
       [0.78873067],
       [0.5181496 ],
       [0.43632065]])

In [54]:
# compute average MSE cost over all input vectors
nn.getCost(inputs,targets)

1.7771013151641077

Exercise: Copy the above NN class definition and pasted it to a new cell, renaming the class to NN2. Then add a layer of six hidden neurons to it. Modify code in NN2 so that feedforward() and getCost() work on this new architecture. 

In [55]:
# NN with 4 inputs and 5 outputs, featuring two hidden layers

class NN2(object):
    def __init__(self):
        np.random.seed(2021)
        self.w1 = np.random.randn(5,4) # weights matrix with 5 rows and 4 cols for the first layer
        self.b1 = np.random.randn(5,1) # 5 item column vector containing biases for the first layer

        self.w2 = np.random.randn(5, 5) # weights matrix with 5 rows and 5 cols for the first layer
        self.b2 = np.random.randn(5, 1) # 5 item column vector containing biases for the first layer
    
    def feedforward(self, x):
        # Input layer to hidden layer 1
        z_hidden1 = np.dot(self.w1, x.reshape(4, 1)) + self.b1
        a_hidden1 = sigm(z_hidden1)

        # Hidden layer 1 to hidden layer 2, where z of layer 2 is found using the values from layer 1 rather than the input layer
        z_hidden2 = np.dot(self.w2, a_hidden1) + self.b2
        a_hidden2 = sigm(z_hidden2)

        # Values found in the second hidden layer are returned to the user
        return a_hidden2

    def getCost(self, xs, ys):
        cost = 0.0

        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)
            y = ys[i].reshape(5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)
        
            
        return cost/16.0

In [56]:
nn2 = NN2()
print(nn2.w1, '\n')
print(nn.b)

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]
 [ 0.10641374  0.42215483  0.12420684 -0.83795346]
 [ 0.4090157   0.10275122 -1.90772239  1.1002243 ]
 [-1.40232506 -0.22508127 -1.33620597  0.30372151]] 

[[-0.72015884]
 [ 2.5449146 ]
 [ 1.31729112]
 [ 0.0726303 ]
 [-0.25610814]]


In [57]:
nn2.feedforward(inputs[0].reshape(4, 1))

array([[0.95275262],
       [0.74465632],
       [0.06203023],
       [0.37010613],
       [0.68936733]])