This a makey-upey neural network with 1 layer of 5 neurons which is the output layer.
Each input has 4 values and is associated with desired output with 5 values. All this requires a 5 by 4 weight matrix.
16 sample inputs and corresponding desired outputs are provided.

Yout task is to write code for feedforward() and getCost().

Then you are finally asked to add another layer to the network.

In [12]:
import numpy as np

def sigm(z):
    return 1.0 / (1.0 + np.exp(-z))

In [13]:
inputs = np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],
                [0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],
                [1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],
                [1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])

# These target vectors or desired output have no meaning.
targets = np.array([[1,0,0,0,0],[1,0,0,0,0],[0,1,0,0,0],[0,1,0,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,1,0,0,0],[0,0,1,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],
                   [0,0,0,0,1],[0,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0]])
print(inputs, '\n')
print(inputs.shape, '\n')
print(targets, '\n')
print(targets.shape)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] 

(16, 4) 

[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]] 

(16, 5)


In [14]:
# NN with 4 inputs and 5 outputs

class NN(object):
    def __init__(self):
        np.random.seed(2021)
        self.w = np.random.randn(5,4)
        self.b = np.random.randn(5,1)
    
    def feedforward(self, x):
        # Input layer to hidden layer
        z_hidden = np.dot(self.w, x.reshape(4, 1)) + self.b
        a_hidden = sigm(z_hidden)

        return a_hidden

    def getCost(self, xs, ys):
        cost = 0.0
        # Note that each input x from xs and corresponding desired output y from ys
        # are vectors of shape (4,) and (5,). They must first be rehaped into column
        # vectors of shapes (4,1) and (5,1).

        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)
            y = ys[i].reshape(5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)
        
            
        return cost/16.0

In [15]:
nn = NN()
print(nn.w, '\n')
print(nn.b)

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]
 [ 0.10641374  0.42215483  0.12420684 -0.83795346]
 [ 0.4090157   0.10275122 -1.90772239  1.1002243 ]
 [-1.40232506 -0.22508127 -1.33620597  0.30372151]] 

[[-0.72015884]
 [ 2.5449146 ]
 [ 1.31729112]
 [ 0.0726303 ]
 [-0.25610814]]


In [16]:
# Test feed forward on first input vector
# The input vector (shape 4,) must first be reshaped to a column vector (shape 4,1)
nn.feedforward(inputs[0].reshape(4,1))

array([[0.32735801],
       [0.92723113],
       [0.78873067],
       [0.5181496 ],
       [0.43632065]])

In [17]:
# compute average MSE cost over all input vectors
nn.getCost(inputs,targets)

1.7771013151641077

Exercise: Copy the above NN class definition and pasted it to a new cell, renaming the class to NN2. Then add a layer of six hidden neurons to it. Modify code in NN2 so that feedforward() and getCost() work on this new architecture. 

In [19]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

class NN2(object):
    def __init__(self):
        np.random.seed(2021)
        self.w1 = np.random.randn(6, 4)  # Weight matrix for the first layer (6 neurons, 4 inputs)
        self.b1 = np.random.randn(6, 1)  # Bias matrix for the first layer (6 neurons)

        self.w2 = np.random.randn(5, 6)  # Weight matrix for the second layer (5 outputs, 6 hidden neurons)
        self.b2 = np.random.randn(5, 1)  # Bias matrix for the second layer (5 outputs)

    def feedforward(self, x):
        # Input layer to the first hidden layer
        z_hidden1 = np.dot(self.w1, x.reshape(4, 1)) + self.b1
        a_hidden1 = sigmoid(z_hidden1)

        # First hidden layer to the output layer
        z_hidden2 = np.dot(self.w2, a_hidden1) + self.b2
        a_hidden2 = sigmoid(z_hidden2)

        return a_hidden2

    def getCost(self, xs, ys):
        cost = 0.0

        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)
            y = ys[i].reshape(5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)

        return cost / (2 * len(xs))

# Example usage:
nn = NN2()
sample_inputs = np.random.rand(16, 4)
desired_outputs = np.random.rand(16, 5)

cost = nn.getCost(sample_inputs, desired_outputs)
print("Initial Cost:", cost)

# You can now use the feedforward function to get the output of the network for a given input:
input_example = np.random.rand(4)
output_example = nn.feedforward(input_example)
print("Output for the given input:", output_example)


Initial Cost: 0.4765358741901054
Output for the given input: [[0.97469598]
 [0.09851562]
 [0.88229178]
 [0.1710569 ]
 [0.47492136]]
