This a makey-upey neural network with 1 layer of 5 neurons which is the output layer.
Each input has 4 values and is associated with desired output with 5 values. All this requires a 5 by 4 weight matrix.
16 sample inputs and corresponding desired outputs are provided.

Yout task is to write code for feedforward() and getCost().

Then you are finally asked to add another layer to the network.

In [1]:
import numpy as np

def sigm(z):
    return 1.0 / (1.0 + np.exp(-z))

In [2]:
inputs = np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],
                [0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],
                [1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],
                [1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])

# These target vectors or desired output have no meaning.
targets = np.array([[1,0,0,0,0],[1,0,0,0,0],[0,1,0,0,0],[0,1,0,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,1,0,0,0],[0,0,1,0,0],
                   [0,0,1,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],
                   [0,0,0,0,1],[0,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0]])
print(inputs, '\n')
print(inputs.shape, '\n')
print(targets, '\n')
print(targets.shape)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] 

(16, 4) 

[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]] 

(16, 5)


In [ ]:
# NN with 4 inputs and 5 outputs

class NN(object):
    def __init__(self):
        np.random.seed(2021)
        self.w = np.random.randn(5,4)
        self.b = np.random.randn(5,1)
    
    def feedforward(self, x):
        
        return 

    def getCost(self, xs, ys):
        cost = 0.0
        # Note that each input x from xs and corresponding desired output y from ys
        # are vectors of shape (4,) and (5,). They must first be rehaped into column
        # vectors of shapes (4,1) and (5,1).
        
            
        return cost/16.0

In [ ]:
nn = NN()
print(nn.w, '\n')
print(nn.b)

In [ ]:
# Test feed forward on first input vector
# The input vector (shape 4,) must first be reshaped to a column vector (shape 4,1)
nn.feedforward(inputs[0].reshape(4,1))

In [ ]:
# compute average MSE cost over all input vectors
nn.getCost(inputs,targets)

Exercise: Copy the above NN class definition and pasted it to a new cell, renaming the class to NN2. Then add a layer of six hidden neurons to it. Modify code in NN2 so that feedforward() and getCost() work on this new architecture. 